### ISSUE TITLE
Error in DiagnosticAssembly.Execute(string argument)

### ISSUE THREAD

**Issue by CrazyBaran** [kkokosa/Tune#12]
I try execute sample code from Open file and I get error:

Merge operation failed return code 0x2

Script execution failed: System.ApplicationException: Merge operation failed return code 0x2
   w Microsoft.Diagnostics.Tracing.Session.TraceEventSession.Merge(String[] inputETLFileNames, String outputETLFileName, TraceEventMergeOptions options)
   w Microsoft.Diagnostics.Tracing.Session.TraceEventSession.MergeInPlace(String etlFileName, TextWriter log)
   w Tune.Core.Collectors.ClrEtwCollector.Stop() w C:\TestAndOtherStuff\TUNE\Tune.Core\Collectors\ClrEtwCollector.cs:wiersz 62
   w Tune.Core.Collectors.ClrEtwCollector.Dispose() w C:\TestAndOtherStuff\TUNE\Tune.Core\Collectors\ClrEtwCollector.cs:wiersz 159
   w Tune.Core.DiagnosticAssembly.Execute(String argument) w C:\TestAndOtherStuff\TUNE\Tune.Core\DiagnosticAssembly.cs:wiersz 75

**Comment by kkokosa** [comment]
@CrazyBaran thank you for the report. Could you try to run it as an administrator?

**Comment by CrazyBaran** [comment]
I try Run as Administrator and the same, but I think i don't have real administrator on this machine in work.

**Comment by kkokosa** [comment]
This may be the reason. Could you check, at the time of the error, the size of files `data.etl` and `data.kernel.etl` in the program directory?

**Comment by CrazyBaran** [comment]
Before error I have only file data.clrRundown.etl size: 73 664 KB, after the same. Breakpoint in line 62 in file ClrEtwCollector.cs .

**Comment by kkokosa** [comment]
I've created issue #14 to remember about better handling of this. BTW could you check `elevated` value at ClrEtwCollector.cs:line 86 ?

**Comment by CrazyBaran** [comment]
When i don't made Run as Administrator it is of course false, but when i made it, it is true, even with my doubtful administrator right on work.

BTW. I am thankful for this project, I  looking long for some small project where I could watch and help with development processes from beginning even as tester.

**Comment by kkokosa** [comment]
You are welcome! This is small project and with its current 0.3 version there will be a lot of testing possible altogether with small fixes contributions:)

**Comment by CrazyBaran** [comment]
I test it at home and the same. I think the problem is that data.etl doesn't exist. I copy data.clrRundown.etl change name into data.etl and no error.
